git: update credential helpers

diff --git a/home/.local/libexec/github-credential-helper b/home/.local/libexec/github-credential-helper
--- a/home/.local/libexec/github-credential-helper
+++ b/home/.local/libexec/github-credential-helper
@@ -2,14 +2,41 @@
 
 set -euo pipefail
 
-readonly TOKEN_FILE=$HOME/.config/github/helper-access-token
-
-if [[ -e $TOKEN_FILE ]]; then
-    source "$TOKEN_FILE"
-
-    printf 'password=%s\n' "$GITHUB_TOKEN"
-
-    if [[ -n ${GITHUB_USER:-} ]]; then
-        printf 'username=%s\n' "$GITHUB_USER"
-    fi
+if [[ ${1:-} != get ]]; then
+    exit 0
 fi
+
+declare -A CRED=()
+while IFS='=' read -r key value; do
+    if [[ -n ${key:-} ]]; then
+        CRED[$key]=$value
+    else
+        break
+    fi
+done
+
+USERNAME=flrgh
+
+HOST=${CRED[host]:-}
+REF=
+
+case $HOST in
+    github.com|gist.github.com|api.github.com)
+        REF=bws://main/github-helper-token
+        ;;
+    git.pancakes2.com)
+        REF=bws://home/gitea-access-token
+        ;;
+    *)
+        exit 0
+        ;;
+esac
+
+TOKEN=$(secrets get --cache "$REF")
+if [[ -z ${TOKEN:-} ]]; then
+    echo "ERROR: failed fetching token for $HOST" >&2
+    exit 1
+fi
+
+printf 'username=%s\n' "$USERNAME"
+printf 'password=%s\n' "$TOKEN"
